MASTER_CHAPTER_DATABASE = {
    "MATH": [
        # Class 11
        {"id": "M1101", "name": "Sets, Relations and Functions"},
        {"id": "M1102", "name": "Trigonometric Functions"},
        {"id": "M1103", "name": "Complex Numbers and Quadratic Equations"},
        {"id": "M1104", "name": "Linear Inequalities"},
        {"id": "M1105", "name": "Permutations and Combinations"},
        {"id": "M1106", "name": "Binomial Theorem"},
        {"id": "M1107", "name": "Sequences and Series"},
        {"id": "M1108", "name": "Straight Lines"},
        {"id": "M1109", "name": "Conic Sections"},
        {"id": "M1110", "name": "Introduction to Three-Dimensional Geometry"},
        {"id": "M1111", "name": "Limits and Derivatives"},
        {"id": "M1112", "name": "Statistics and Probability"},
        # Class 12
        {"id": "M1201", "name": "Inverse Trigonometric Functions"},
        {"id": "M1202", "name": "Matrices and Determinants"},
        {"id": "M1203", "name": "Continuity and Differentiability"},
        {"id": "M1204", "name": "Application of Derivatives"},
        {"id": "M1205", "name": "Integrals (Definite and Indefinite)"},
        {"id": "M1206", "name": "Application of Integrals"},
        {"id": "M1207", "name": "Differential Equations"},
        {"id": "M1208", "name": "Vector Algebra"},
        {"id": "M1209", "name": "Three-Dimensional Geometry (Vectors)"},
        {"id": "M1210", "name": "Linear Programming"},
        {"id": "M1211", "name": "Probability (Advanced)"}
    ],
    "PHYSICS": [
        # Class 11
        {"id": "P1101", "name": "Units and Measurements"},
        {"id": "P1102", "name": "Motion in a Straight Line"},
        {"id": "P1103", "name": "Motion in a Plane (Vectors & Projectiles)"},
        {"id": "P1104", "name": "Laws of Motion and Friction"},
        {"id": "P1105", "name": "Work, Energy and Power"},
        {"id": "P1106", "name": "System of Particles and Rotational Motion"},
        {"id": "P1107", "name": "Gravitation"},
        {"id": "P1108", "name": "Mechanical Properties of Solids"},
        {"id": "P1109", "name": "Mechanical Properties of Fluids"},
        {"id": "P1110", "name": "Thermal Properties of Matter"},
        {"id": "P1111", "name": "Thermodynamics"},
        {"id": "P1112", "name": "Kinetic Theory of Gases"},
        {"id": "P1113", "name": "Oscillations (SHM)"},
        {"id": "P1114", "name": "Waves and Acoustics"},
        # Class 12
